name: CMake Build for Doxygen

on: [push, pull_request]

jobs:
  build:
    permissions:
      contents: write # to push pages branch (peaceiris/actions-gh-pages)

    name: ${{ format('{0} {1} {2}', matrix.config.os, matrix.build_type, matrix.config.cc) }}
    runs-on: ${{ matrix.config.os }}
    env:
      JOB_NAME: ${{ format('{0} {1} {2}', matrix.config.os, matrix.build_type, matrix.config.cc) }}
    strategy:
      fail-fast: false
      matrix:
       build_type: ["Debug", "Release"]
       config:
          - { os: ubuntu-20.04, cc: "gcc", cxx: "g++", build_gen: "Unix Makefiles",
              cmake_extra_opts: "-Dbuild_search=YES -Dbuild_app=YES -Dbuild_parse=YES -Dbuild_xmlparser=YES -Duse_sqlite3=ON",
              tools: { bison: 'bison', flex: 'flex', gs: 'gs' },
            }
          - { os: ubuntu-20.04, cc: "clang", cxx: "clang++", build_gen: "Unix Makefiles",
              cmake_extra_opts: "-Duse_libclang=YES -Dstatic_libclang=YES -Duse_libc++=NO -Duse_sqlite3=ON",
              tools: { bison: 'bison', flex: 'flex', gs: 'gs' },
            }
          - { os: macos-latest, cc: "clang", cxx: "clang++", build_gen: "Unix Makefiles",
              tools: { bison: 'bison', flex: 'flex', gs: 'gs' },
            }
          - { os: windows-latest, cc: "cl", cxx: "cl", build_gen: "NMake Makefiles",
              tools: { bison: 'win_bison', flex: 'win_flex', gs: 'gswin64c' },
              extra_ctest_flags: '--pdf',
            }
    steps:
    - name: Checkout doxygen
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

#    - name: Download MikTex (Windows)
#      if: runner.os == 'windows'
#      run: |
#        $wc = New-Object System.Net.WebClient;
#        $maxAttempts=5;
#        $attemptCount=0;
#        Do {
#          $attemptCount++;
#          Try {
#            $wc.DownloadFile("https://ctan.math.illinois.edu/systems/win32/miktex/setup/windows-x64/miktexsetup-5.2.0+b8f430f-x64.zip","miktexsetup-5.2.0+b8f430f-x64.zip")
#          } Catch [Exception] {
#            Write-Host $_.Exception | format-list -force
#          }
#        } while (((Test-Path "miktexsetup-5.2.0+b8f430f-x64.zip") -eq $false) -and ($attemptCount -le $maxAttempts))
#      shell: pwsh

    - name: Install libiconv (Windows)
      if: runner.os == 'windows'
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/pffang/libiconv-for-Windows/releases/download/v1.16/libiconv-for-Windows_1.16.7z"
        target: .

    - name: Install LaTeX (Linux)
      if: runner.os == 'linux'
      run: |
        sudo apt update
        sudo apt-get install texlive texlive-latex-recommended texlive-extra-utils texlive-latex-extra texlive-font-utils

    - name: Install GhostScript & Poppler (macOS)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install --overwrite ghostscript poppler

    - name: Install LaTeX (MacOS)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install --cask basictex
        echo "/Library/TeX/texbin/" >> $GITHUB_PATH

    - name: Install LaTeX Packages (macOS)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install --cask gpg-suite-no-mail  # For tlmgr signatures
        sudo tlmgr update --self
        sudo tlmgr install \
             adjustbox alphalph appendix collectbox dvisvgm enumitem \
             epstopdf etoc hanging ifoddpage import listofitems \
             multirow newunicodechar plantuml pdftex regexpatch sectsty \
             stackengine svg tocloft varwidth wasysym

    - name: Install libclang (Ubuntu 20.04)
      if: runner.os == 'linux' && matrix.config.cc == 'clang'
      run: |
        sudo apt update
        sudo apt remove llvm-8 clang-8 libclang-common-8-dev clang-format-8 libllvm8
        sudo apt remove llvm-9 llvm-9-dev llvm-9-tools llvm-9-runtime clang-9 libclang-common-9-dev clang-format-9 libllvm9
        #sudo apt remove llvm-10 llvm-10-dev llvm-10-tools llvm-10-runtime clang-10 clang-format-10 libclang-common-10-dev libclang-cpp10 libclang1-10 libllvm10
        sudo apt remove llvm-11 llvm-11-dev llvm-11-tools llvm-11-runtime clang-11 clang-format-11 libclang-common-11-dev libclang-cpp11 libclang1-11 libllvm11
        sudo apt remove llvm-12 llvm-12-dev llvm-12-tools llvm-12-runtime clang-12 clang-format-12 libclang-common-12-dev libclang-cpp12 libclang1-12 libllvm12
        sudo apt-get autoremove
        sudo apt-get clean
        sudo apt install libclang-common-10-dev libclang-10-dev
        apt list --installed | egrep '(clang|llvm)'
        ls -d /usr/lib/llvm-*/include/
        sudo update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-10   100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-10 100
        ls -al /usr/bin/clang++
        ls -al /etc/alternatives/clang++
        which clang++
        clang++ -v

    - name: Install libxapian (Ubuntu)
      if: runner.os == 'linux'
      run: |
        sudo apt update
        sudo apt install libxapian-dev

#    - name: Extract MikTex zip (Windows)
#      if: runner.os == 'windows'
#      shell: bash
#      run: |
#        unzip miktexsetup-5.2.0+b8f430f-x64.zip
#
#    - name: Download MikTex packages (Windows)
#      if: runner.os == 'windows'
#      shell: bash
#      run: |
#        ./miktexsetup_standalone --verbose \
#                      --local-package-repository="C:/miktex-repository" \
#                      --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" \
#                      --package-set=essential \
#                      download
#
#    - name: Install MikTex packages (Windows)
#      if: runner.os == 'windows'
#      shell: bash
#      run: |
#        ./miktexsetup_standalone --local-package-repository="C:/miktex-repository" \
#                      --verbose \
#                      --package-set=essential \
#                      --shared \
#                      install
#
#    - name: Setting MikTex paths (Windows)
#      if: runner.os == 'windows'
#      shell: bash
#      run: |
#        echo "C:/Program Files/MiKTeX/miktex/bin/x64/" >> $GITHUB_PATH
#        export PATH="/c/Program Files/MiKTeX/miktex/bin/x64/:$PATH"
#
#        echo "Configuring MiKTeX to install missing packages on the fly"
#        initexmf --admin --verbose --set-config-value='[MPM]AutoInstall=1'

    - name: Install LaTeX (Windows)
      if: runner.os == 'windows'
      uses: teatimeguest/setup-texlive-action@v2
      with:
        packages: >-
          scheme-medium
          collection-latexextra
          babel-dutch
          cjk
          bibtex

    - name: Install Ghostscript (Linux)
      if: runner.os == 'linux'
      run: |
        sudo apt update
        sudo apt-get install ghostscript

    - name: Install Ghostscript (Windows)
      if: runner.os == 'windows'
      run:
        choco install ghostscript

    - name: Setting Ghostscript paths (Windows)
      if: runner.os == 'windows'
      shell: bash
      run: |
        _gsloc="$(dirname "$(find /c/Prog*/gs -iname gswin\*c.exe)")"
        echo "$(cygpath -w "${_gsloc}")" >> $GITHUB_PATH

    - name: Install xmllint (Linux)
      if: runner.os == 'linux'
      run: |
         sudo apt-get update
         sudo apt-get install libxml2-utils

    - name: Install xmllint (MacOS)
      run: |
         brew update
         brew install --overwrite libxml2
      if: runner.os == 'macos'

    - name: Install bison (MacOS)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install --overwrite bison
        echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH

    - name: Install bison/flex (Windows)
      if: runner.os == 'windows'
      run: |
        Choco-Install -PackageName winflexbison
        #choco install winflexbison

    - name: Install Graphviz (Linux)
      if: runner.os == 'linux'
      run: |
        sudo apt update
        sudo apt-get install graphviz

    - name: Install Graphviz (MacOS)
      if: runner.os == 'macos'
      run: |
        brew install --overwrite graphviz

    - name: Install Graphviz (Windows)
      if: runner.os == 'windows'
      run: |
        choco install graphviz.portable

#    - name: Install Perl (Windows)
#      if: runner.os == 'windows'
#      run:
#        choco install activeperl

    - name: Setup VS Environment (Windows)
      if: runner.os == 'windows'
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Refresh Env (Windows)
      if: runner.os == 'windows'
      run:
        refreshenv

    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Check tool versions
      shell: bash
      run: |
        echo "Build tools for $JOB_NAME:";
        echo "=== perl ===";
        perl --version;
        echo "=== python ===";
        python --version;
        echo "=== cmake ===";
        cmake --version;
        echo "=== latex ===";
        latex --version;
        echo "=== bibtex ===";
        bibtex --version
        echo "=== dvips ===";
        dvips --version
        echo "=== bison ===";
        ${{ matrix.config.tools.bison }} --version;
        echo "=== flex ===";
        ${{ matrix.config.tools.flex }} --version;
        echo "=== dot ===";
        dot -V;
        echo "=== ghostscript ===";
        ${{ matrix.config.tools.gs }} --version;

    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${{ matrix.config.cc }})
        set(ENV{CXX} ${{ matrix.config.cxx }})

        execute_process(
          COMMAND cmake
            -S .
            -B build
            -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -G "${{ matrix.config.build_gen }}"
            -Dbuild_doc=YES
            -Dbuild_wizard=YES
            ${{ matrix.config.cmake_extra_opts }}
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

    - name: Build
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)
        execute_process(
          COMMAND cmake --build build --parallel ${N}
          RESULT_VARIABLE result
          OUTPUT_VARIABLE output
          ERROR_VARIABLE output
          ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE
        )
        if (NOT result EQUAL 0)
          string(REGEX MATCH "FAILED:.*$" error_message "${output}")
          string(REPLACE "\n" "%0A" error_message "${error_message}")
          message("::error::${error_message}")
          message(FATAL_ERROR "Build failed")
        endif()

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: '${{ env.JOB_NAME }} build artifacts'
        path: build/bin/

    - name: Run tests
      shell: cmake -P {0}
      run: >+
        set(ENV{CTEST_OUTPUT_ON_FAILURE} "ON")

        execute_process(
          COMMAND
            cmake --build build --target tests
            TEST_FLAGS="--xml --xmlxsd --xhtml --qhp --docbook --rtf ${{ matrix.config.extra_ctest_flags }}"
          RESULT_VARIABLE result)

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()

    - name: Generate documentation
      if: runner.os == 'linux' && matrix.build_type == 'release' && matrix.config.cc == 'gcc'
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake --build build --target docs
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Building documentation failed")
        endif()

    - name: Archive html documentation artifacts
      if: runner.os == 'linux' && matrix.build_type == 'release' && matrix.config.cc == 'gcc'
      uses: actions/upload-artifact@v3
      with:
        name: "Html documentation artifacts"
        path: build/html/


    - name: Archive Latex documentation artifacts
      if: runner.os == 'linux' && matrix.build_type == 'release' && matrix.config.cc == 'gcc'
      uses: actions/upload-artifact@v3
      with:
        name: "Latex documentation artifacts"
        path: build/latex/doxygen_manual.pdf

    - name: Generate Internal documentation
      if: runner.os == 'linux' && matrix.build_type == 'release' && matrix.config.cc == 'gcc'
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake --build build --target docs_internal
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Building internal documentation failed")
        endif()

    - name: Publish Internal documentation to Github pages
      if: github.event_name == 'push' && runner.os == 'linux' && matrix.build_type == 'release' && matrix.config.cc == 'gcc'
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: build/doxygen_docs/html
